'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import cytoscape from 'cytoscape';
import novelData from '../data/qingshan-ch1-30.json';

const typeColors={親屬:'#f59e0b',婚姻:'#ec4899',師徒:'#22c55e',同門:'#84cc16',同僚:'#ef4444',敵對:'#ef4444',死敵:'#ef4444',衝突:'#ef4444',加害:'#ef4444',勾結:'#a855f7',侍從:'#f472b6',醫患:'#38bdf8',命運:'#8b5cf6',神秘聯繫:'#8b5cf6',契約:'#8b5cf6',救命:'#f97316',情報交易:'#06b6d4',查案:'#38bdf8',審訊:'#a855f7',賞識:'#22d3ee',行官夥伴:'#0891b2',行官啟蒙:'#0891b2',親近:'#f59e0b',監視:'#64748b'};

export default function CharacterGraph(){
 const ref=useRef(null),cyRef=useRef(null);
 const [chapter,setChapter]=useState(30),[spoiler,setSpoiler]=useState(1),[search,setSearch]=useState(''),[selected,setSelected]=useState(null),[neighbor,setNeighbor]=useState(false),[counts,setCounts]=useState({nodes:0,edges:0}),[groups,setGroups]=useState(()=>new Set(Object.keys(novelData.groups)));
 const selectedData=useMemo(()=>novelData.characters.find(x=>x.id===selected)||null,[selected]);
 useEffect(()=>{if(!ref.current||cyRef.current)return;const elements=[...novelData.characters.map(n=>({data:{...n,color:novelData.groups[n.group]}})),...novelData.relations.map(e=>({data:{...e,color:typeColors[e.type]||'#64748b'}}))];const cy=cytoscape({container:ref.current,elements,style:[{selector:'node',style:{'background-color':'data(color)',label:'data(name)',color:'#e5edf8','font-size':11,'text-valign':'bottom','text-margin-y':7,width:34,height:34,'border-width':2,'border-color':'#dbeafe','text-outline-width':2,'text-outline-color':'#07111f'}},{selector:'node[importance="major"]',style:{width:48,height:48,'font-size':13,'font-weight':700}},{selector:'edge',style:{'curve-style':'bezier',width:2,'line-color':'data(color)','target-arrow-color':'data(color)','target-arrow-shape':'triangle','arrow-scale':.7,label:'data(label)','font-size':8,color:'#9fb0c6','text-background-color':'#07111f','text-background-opacity':.8,'text-background-padding':2,'text-rotation':'autorotate'}},{selector:'edge[type="親屬"],edge[type="婚姻"],edge[type="同門"],edge[type="同僚"]',style:{'target-arrow-shape':'none'}},{selector:'edge[type="敵對"],edge[type="死敵"],edge[type="衝突"],edge[type="加害"],edge[type="危險合作"]',style:{'line-style':'dashed'}},{selector:':selected',style:{'border-width':5,'border-color':'#f8fafc'}},{selector:'.hidden',style:{display:'none'}},{selector:'.faded',style:{opacity:.12,'text-opacity':0}}],layout:{name:'cose',animate:false,idealEdgeLength:115,nodeRepulsion:480000,gravity:.35,randomize:true}});cy.on('tap','node',e=>{setSelected(e.target.id());setNeighbor(false)});cy.on('tap',e=>{if(e.target===cy){setSelected(null);setNeighbor(false)}});cyRef.current=cy;return()=>{cy.destroy();cyRef.current=null}},[]);
 useEffect(()=>{const cy=cyRef.current;if(!cy)return;cy.elements().removeClass('hidden faded');cy.nodes().forEach(n=>{if(n.data('firstChapter')>chapter||!groups.has(n.data('group')))n.addClass('hidden')});cy.edges().forEach(e=>{const s=cy.getElementById(e.data('source')),t=cy.getElementById(e.data('target'));if(e.data('firstChapter')>chapter||e.data('spoiler')>spoiler||s.hasClass('hidden')||t.hasClass('hidden'))e.addClass('hidden')});if(neighbor&&selected){const n=cy.getElementById(selected);if(n.length&&n.visible()){const keep=n.closedNeighborhood().filter(':visible');cy.elements(':visible').not(keep).addClass('hidden')}}const q=search.trim().toLowerCase();if(q){const m=cy.nodes(':visible').filter(n=>`${n.data('name')} ${n.data('alias')||''}`.toLowerCase().includes(q));if(m.length)cy.elements(':visible').not(m.closedNeighborhood()).addClass('faded')}setCounts({nodes:cy.nodes(':visible').length,edges:cy.edges(':visible').length});setTimeout(()=>cy.fit(cy.elements(':visible'),45),30)},[chapter,spoiler,search,groups,selected,neighbor]);
 const toggle=g=>setGroups(prev=>{const next=new Set(prev);next.has(g)?next.delete(g):next.add(g);return next});
 const rels=useMemo(()=>{if(!selectedData)return[];return novelData.relations.filter(r=>(r.source===selectedData.id||r.target===selectedData.id)&&r.firstChapter<=chapter&&r.spoiler<=spoiler).map(r=>({...r,other:novelData.characters.find(c=>c.id===(r.source===selectedData.id?r.target:r.source))})).filter(r=>r.other&&groups.has(r.other.group)&&r.other.firstChapter<=chapter)},[selectedData,chapter,spoiler,groups]);
 const layout=()=>cyRef.current?.elements(':visible').layout({name:'cose',animate:true,animationDuration:500,idealEdgeLength:115,nodeRepulsion:480000,gravity:.35,randomize:true}).run();
 return <div className="app"><aside className="side"><h1 className="title">《青山》人物關係圖</h1><p className="subtitle">會說話的肘子｜目前整理第 1～30 章</p><label className="label">搜尋人物</label><input className="control" value={search} onChange={e=>setSearch(e.target.value)} placeholder="陳跡、袍哥、烏雲……"/><label className="label">閱讀進度（防劇透）</label><div className="chapter"><input className="range" type="range" min="1" max="30" value={chapter} onChange={e=>setChapter(+e.target.value)}/><span className="badge">第{chapter}章</span></div><label className="label">關係劇透程度</label><select className="control" value={spoiler} onChange={e=>setSpoiler(+e.target.value)}><option value={0}>只顯示明面關係</option><option value={1}>顯示一般劇透</option><option value={2}>顯示重大劇透</option></select><span className="label">人物陣營</span>{Object.entries(novelData.groups).map(([g,c])=><label className="group" key={g}><input type="checkbox" checked={groups.has(g)} onChange={()=>toggle(g)}/><span className="dot" style={{background:c}}/>{g}</label>)}<div className="buttons"><button className="button" onClick={()=>cyRef.current?.fit(cyRef.current.elements(':visible'),45)}>全部置中</button><button className="button" onClick={()=>selected&&setNeighbor(true)}>只看周邊</button><button className="button" onClick={()=>{setSelected(null);setNeighbor(false);setSearch('')}}>恢復全圖</button><button className="button" onClick={layout}>重新排列</button></div><p className="help">點擊人物查看資料。滑鼠滾輪或雙指可縮放；拖曳人物可調整位置。</p></aside><main className="main"><div className="floating"><span>顯示 {counts.nodes} 人／{counts.edges} 條關係</span></div><div ref={ref} className="canvas"/></main><section className="detail">{selectedData?<><h2>{selectedData.name}</h2><p className="subtitle">{selectedData.alias}｜{selectedData.group}｜初登場第 {selectedData.firstChapter} 章</p><div className="card"><h3>人物狀態</h3>{selectedData.status}</div><div className="card"><h3>人物簡介</h3>{selectedData.description}</div><div className="card"><h3>目前可見關係（{rels.length}）</h3>{rels.length?rels.map(r=><div className="relation" key={r.id}><strong>{r.other.name}</strong><br/>{r.type}：{r.label}（第 {r.firstChapter} 章）</div>):<span className="muted">目前設定下沒有可見關係。</span>}</div></>:<p className="muted">請點擊人物節點，這裡會顯示人物介紹與目前章節可見的關係。</p>}</section></div>
}
